/**
 * Local Provider - Discovers skills from local filesystem directories.
 *
 * Searches ~/.claude/skills/ and other agent-specific skill directories
 * for existing SKILL.md files.
 *
 * Ported from Python core/providers/local_provider.py.
 */

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import yaml from "yaml";
import type { SkillSearchResult } from "../../types";
import type { SkillProvider } from "./base";

/**
 * Parse a SKILL.md file into a SkillSearchResult.
 *
 * @param skillFile - Absolute path to a SKILL.md file.
 * @returns Parsed SkillSearchResult, or null if parsing fails.
 */
function parseSkill(skillFile: string): SkillSearchResult | null {
  try {
    const content = fs.readFileSync(skillFile, "utf-8");
    if (!content.startsWith("---")) {
      return null;
    }

    const parts = content.split("---", 3);
    if (parts.length < 3) {
      return null;
    }

    const frontmatter: Record<string, unknown> = yaml.parse(parts[1]) ?? {};

    const dirName = path.basename(path.dirname(skillFile));
    const name =
      typeof frontmatter.name === "string" ? frontmatter.name : dirName;
    const description =
      typeof frontmatter.description === "string"
        ? frontmatter.description
        : "";

    let tags: string[] = [];
    if (Array.isArray(frontmatter.tags)) {
      tags = frontmatter.tags.map(String);
    } else if (typeof frontmatter.tags === "string") {
      tags = frontmatter.tags.split(",").map((t: string) => t.trim());
    }

    const confidence =
      typeof frontmatter.confidence === "number"
        ? frontmatter.confidence
        : 0.8;

    return {
      id: name,
      name,
      description,
      source: "local",
      confidence,
      author: "",
      tags,
      installCount: 0,
      sourceUrl: "",
      compatibleAgents: [],
      metadata: {
        path: skillFile,
        autoGenerated: frontmatter["auto-generated"] === true,
      },
    };
  } catch {
    return null;
  }
}

/**
 * Create a local filesystem skill provider.
 *
 * Searches configured directories for SKILL.md files and matches
 * against skill name, description, and tags.
 *
 * @param skillDirs - List of directories containing skills.
 *   Defaults to [`~/.claude/skills`].
 * @returns A SkillProvider backed by local filesystem.
 */
export function createLocalProvider(skillDirs?: string[]): SkillProvider {
  const dirs =
    skillDirs ?? [path.join(os.homedir(), ".claude", "skills")];

  return {
    name: "Local Skills",
    sourceId: "local",

    async search(
      query: string,
      limit: number = 10,
    ): Promise<SkillSearchResult[]> {
      const results: SkillSearchResult[] = [];
      const queryLower = query.toLowerCase();

      for (const dir of dirs) {
        if (!fs.existsSync(dir)) {
          continue;
        }

        let entries: fs.Dirent[];
        try {
          entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
          continue;
        }

        for (const entry of entries) {
          if (!entry.isDirectory()) {
            continue;
          }

          const skillFile = path.join(dir, entry.name, "SKILL.md");
          if (!fs.existsSync(skillFile)) {
            continue;
          }

          const result = parseSkill(skillFile);
          if (result === null) {
            continue;
          }

          // Match against name, description, or tags
          const searchable =
            `${result.name} ${result.description} ${result.tags.join(" ")}`.toLowerCase();
          if (queryLower && !searchable.includes(queryLower)) {
            continue;
          }

          results.push(result);
          if (results.length >= limit) {
            break;
          }
        }

        if (results.length >= limit) {
          break;
        }
      }

      return results;
    },

    async getSkillDetails(
      skillId: string,
    ): Promise<SkillSearchResult | null> {
      for (const dir of dirs) {
        if (!fs.existsSync(dir)) {
          continue;
        }
        const skillPath = path.join(dir, skillId, "SKILL.md");
        if (fs.existsSync(skillPath)) {
          return parseSkill(skillPath);
        }
      }
      return null;
    },

    isAvailable(): boolean {
      return true;
    },
  };
}
